### ISSUE TITLE
propagate `firstMatch` parameter in `get_indexes_from_names()` upstream

### ISSUE THREAD

**Issue by keviny2** [BiocPy/SummarizedExperiment#27]
currently, [`get_indexes_from_names()`](https://github.com/BiocPy/SummarizedExperiment/blob/4c66f65a56bef49f611db746668b663c48a1ca46/src/summarizedexperiment/utils/_slicer.py#L11) simply returns the first occurrence. sometimes it may be useful to concatenate the values for duplicates.

**Comment by jkanche** [comment]
that function already supports that, this should be about how we propagate that parameter upstream to the slice operator `[...]`

**Comment by jkanche** [comment]
the new combine operations do not not need this.
