### ISSUE TITLE
Support GenomicRangesList

### ISSUE THREAD

**Issue by DiDeoxy** [BiocPy/SummarizedExperiment#35]
https://github.com/BiocPy/SummarizedExperiment/blob/b371946a149e09d6ee91778ce0da4635f3c1c7bb/src/summarizedexperiment/RangedSummarizedExperiment.py#L95

@jkanche Needs to support `GenomicRangesList` as well :) (same with `RangedSingleCellExperiment`).

**Comment by jkanche** [comment]
#36 should suffice for now. a much deeper integration is needed once GRL is fully implemented.
