### ISSUE TITLE
Eliminate scipy dependency

### ISSUE THREAD

**Issue by LTLA** [BiocPy/SummarizedExperiment#46]
Only needed to apply a restriction on the type, which is unnecessary:

https://github.com/BiocPy/SummarizedExperiment/blob/e01bc9b96b0b8a247c6095daabc701c0818c98ee/src/summarizedexperiment/types.py#L14

**Comment by LTLA** [comment]
Eliminate the initial anndata load as well, only do that if `to_anndata()` is explicitly called.

**Comment by jkanche** [comment]
Done in #52
