### ISSUE TITLE
`in_place` has no effect when `replace_column_names` is also set to True

### ISSUE THREAD

**Issue by DiDeoxy** [BiocPy/SummarizedExperiment#79]
https://github.com/BiocPy/SummarizedExperiment/blob/c7b42c756ab419a87227ac93dafa684ff9bbc36b/src/summarizedexperiment/BaseSE.py#L545-L581

Should either clarify this behaviour in the docstring or implement a fix so that it works as expected.

Also `set_column_data` is type hinted as returning a `BaseSE` this should probably be the object class?

```python
from typing import TypeVar

BSE = TypeVar("BSE", bound=BaseSE)

class BaseSE:
    ...
    def set_column_data(self: BSE, ...) -> BSE:
        ...
    
    ...
```

This will set the type hint to whatever class the object being accessed is (i.e. it will hint the subclass type if the object is a subclass of BaseSE).

**Comment by jkanche** [comment]
Thinking through this for different combinations of `in_place` and `replace_column_names`, 

* True and True: Original object modified directly, column names replaced
* True and False: Original object modified directly, original names preserved
* False and False: New copy created, original names preserved
* False and True: New copy created, names replaced on copy

The last case (False, True) is where your concern applies. Currently, we're making a copy of the object and then replacing column names on that copy. we're only creating one copy total & the column name replacement is happening on that same copy, not creating additional copies.

I think the current behavior makes sense to me. Please feel free to post an MRE if i misunderstood the behavior.

**Comment by DiDeoxy** [comment]
My concern is actually with the scenario where both `replace_column_names` and `in_place` are both `True`, apologies my title is unclear.

Unfortunately, I can't share the code for synthesizing a `SummarizedExperiment` object, but if you have similar code this will demonstrate the issue:

```python
from summarizedexperiment import SummarizedExperiment

def print_column_names(desc: str, se: SummarizedExperiment) -> None:
    """Print the column names of a SummarizedExperiment object."""
    column_names = se.get_column_names()
    if column_names is not None:
        print(column_names[:5], desc)


se = new_se()
print("original")
print_column_names("", se)

new_column_data = new_bioc_frame(se.shape[1])

se1 = se.set_column_data(new_column_data, True)
print("\nreplace_column_names=True, in_place=False")
print_column_names("input", se)
print_column_names("return", se1)

se2 = se.set_column_data(new_column_data, True, True)
print("\nreplace_column_names=True, in_place=True")
print_column_names("input", se)
print_column_names("return", se2)
```

Result:
```sh
original
['Wzv4p', 'JwUtz', 'pM0cN', '9EDHT', 'SuQ1K']

replace_column_names=True, in_place=False
['Wzv4p', 'JwUtz', 'pM0cN', '9EDHT', 'SuQ1K'] input
['dWkbd', 'Yo4TS', '7hJxI', 'yhRJr', '9JPTQ'] return

replace_column_names=True, in_place=True
['Wzv4p', 'JwUtz', 'pM0cN', '9EDHT', 'SuQ1K'] input
['dWkbd', 'Yo4TS', '7hJxI', 'yhRJr', '9JPTQ'] return
```

My expectation for the scenario where `replace_column_names` and `in_place` are both `True` is the the input `SummarizedExperiment` will have the new column names but this is not what occurs. The returned `SummarizedExperiment` has them but the input `SummarizedExperiment` retains the original column names. This is identical to the scenario where `in_place` is `False` which is what I meant by `in_place` having no effect when `replace_column_names` is also set to `True`.

**Comment by jkanche** [comment]
Gotcha, thank you for clarifying this!
